CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS Account (
    id uuid DEFAULT uuid_generate_v4 (),
    name VARCHAR NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    secret VARCHAR NOT NULL, 
    balance INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

